#!/usr/bin/env python3

# Importing the chat class from the talker module
from talker import chat
c = chat.Chat()

# Sobre as aulas:
# O professor fala sobre o tema e o aluno interage com o professor.
# O aluno pode fazer perguntas e o professor responde.
# A conversa deve ser descontraída, o aluno não possui muito conhecimento sobre o assunto, não sabe muito sobre o tema, mas sempre se mostra muito curioso e quer saber as aplicações práticas do tema.
# Os comandos que o professor deve ensinar, serão apenas de exemplo, não serão executados localmente no terminal, mas devem estar conectados com o tema e mostrando cenários práticos.
# Cada comando exposto pelo professor deve ser explicado para o aluno de forma bem informal mas clara.
# O professor deve expor cenários com bom humor, trazendo leveza e descontração para a aula, tentando ao máximo descomplicar o assunto para o aluno.
# O aluno deve interagir com o professor, fazendo perguntas e tirando dúvidas sobre o tema.
# O professor deve ser paciente e explicar o tema de forma que o aluno entenda.
# O aluno deve se sentir à vontade para perguntar e interagir com o professor.
# O professor deve sempre incentivar o aluno a participar e perguntar.
# O professor deve sempre manter o aluno interessado e curioso sobre o tema.
# O professor deve sempre encorajar o aluno a praticar o que foi ensinado. 
# O aluno deve sempre se sentir motivado a aprender mais sobre o tema.
# O professor sempre que possível, deve indicar materiais para o aluno estudar além dessa aula, como links e livros sobre o tema
# Sempre que o aluno entender um tema e trocar para outro tema, deve tentar se despedir do professor e o professor, com uma piada, deve dizer que a aula não terminou e que ele ainda tem muito a aprender.
# A cada Interação e troca de tema, as frases devem ser diferentes para não parecer uma cópia ou repetição durante o dialogo.
# Os alunos devem ser chamados de "padawans", "Pobres", "Padawans", "Pequenos Gafanhotos", "Jovem Tartarugas", "Baby Yoda", "Aprendiz", "Daniel San", "Cavaleiros de Bronze", "Juninho", "Aluninhos", "Newbie", "Iniciante", "Stag" e outros jargões da cultura pop para se referir a aprendizes iniciantes e com muita determinação.

# Deve ser usado sempre que o professor tentar explicar algo
def t(m):
    c.Speak(m)

# Deve ser usado sempre que o aluno quiser fazer um comentário ao professor.
def s(m):
    c.StudentComment(m)

# Deve ser usado sempre que o aluno quiser fazer uma pergunta ao professor.
def q(m):
    c.Question(m)

# Sobre a aula:	é um glossario de termos técnicos que o aluno deve aprender.
# Termos que devem ser explicados, de forma direta, clara, descontraída e com exemplos práticos e em ordem alfabética:
q(f"""{c.Teacher()}, o que é um glossário de termos técnicos?""")
t("""Um glossário de termos técnicos é uma lista de palavras ou frases que são usadas em um determinado campo de conhecimento, juntamente com suas definições e explicações. Serve para ajudar a entender o significado de termos específicos e a melhorar o vocabulário técnico.""")
t("""Aqui está uma lista de termos técnicos que você deve aprender:	(vai buscar um café, a lista é enorme!)""")
t("""Agile:	é uma metodologia de desenvolvimento de software que enfatiza a colaboração, a adaptação a mudanças, a entrega contínua e a melhoria contínua. Serve para colaborar, adaptar, entregar e melhorar continuamente.""")
t("""AI:	é a inteligência artificial, um campo da ciência da computação que se concentra no desenvolvimento de sistemas inteligentes e autônomos. Serve para desenvolver sistemas inteligentes e autônomos. Significa Artificial Intelligence.""")
t("""alerting:	é o envio de alertas e notificações em tempo real para informar sobre problemas e eventos importantes. Serve para informar sobre problemas e eventos importantes.""")
t("""AMQP:	é um protocolo de mensagens avançado, que permite a comunicação assíncrona entre aplicativos. Serve para comunicar de forma assíncrona entre aplicativos. Significa Advanced Message Queuing Protocol.""")
t("""Android:	é um sistema operacional da Google que é amplamente utilizado em dispositivos móveis e tablets. Serve para oferecer suporte a aplicativos e serviços.""")
t("""Ansible:	é uma ferramenta de automação de TI que permite automatizar a implantffffação, a configuração e a orquestração de servidores e aplicativos. Serve para automatizar a implantação, a configuração e a orquestração de servidores e aplicativos. É mantido pela Red Hat.""")
t("""Apache WS:	é um servidor web de código aberto que é projetado para servir conteúdo web de forma eficiente e escalável. Serve para servir conteúdo web de forma eficiente e escalável.""")
t("""API:	é uma interface de programação de aplicativos que permite que diferentes sistemas se comuniquem entre si, permitindo a integração de serviços. Serve para enviar e receber dados entre sistemas.""")
t("""Apigee:	é uma plataforma de gerenciamento de APIs da Google Cloud, que permite a criação, a publicação, a proteção e a análise de APIs. Serve para gerenciar APIs.""")
t("""apk:	é um formato de pacote de código aberto que é projetado para instalar e gerenciar software em sistemas Linux. Serve para instalar e gerenciar software. É nativo das distribuições Alpine.""")
t("""apm:	é o Application Performance Monitoring, um conjunto de ferramentas e técnicas que são usadas para monitorar e otimizar o desempenho de aplicativos. Serve para monitorar e otimizar o desempenho de aplicativos. Significa Application Performance Monitoring.""")
t("""App Mobile:	é um aplicativo desenvolvido para dispositivos móveis, como smartphones e tablets. Serve para criar aplicativos para dispositivos móveis.""")
t("""Apptio:	é uma plataforma de gestão de TI que permite a análise de custos, a otimização de recursos e a tomada de decisões baseadas em dados. Serve para analisar custos e otimizar recursos.""")
t("""Arrow:	é um formato de arquivo de código aberto que é projetado para representar dados de forma eficiente e interoperável. Serve para representar dados de forma eficiente e interoperável. É mantido pela Apache.""")
t("""Async/Await:	é uma sintaxe que permite escrever código assíncrono de forma síncrona, facilitando a leitura e a manutenção do código. Serve para escrever código assíncrono de forma síncrona.""")
t("""Atom:	é um editor de código-fonte que oferece suporte a várias linguagens de programação e extensões para desenvolvimento de software. Serve para desenvolver software. Significa Atom.""")
t("""Avro:	é um formato de arquivo de código aberto que é projetado para serializar e desserializar dados de forma eficiente. Serve para serializar e desserializar dados. É mantido pela Apache.""")
q(f"""Caramba {c.Teacher()}! e temos que aprender tudo isso?""")
t("""Sim, Padawan! Aprender esses termos técnicos é importante para entender melhor o mundo da tecnologia e se comunicar de forma eficaz com outros profissionais da área. Vamos começar com o primeiro termo da lista.""")
t("""AWS API Gateway:	é um serviço de gateway de API da Amazon Web Services, que permite criar, publicar, manter, monitorar e proteger APIs. Serve para criar, publicar, manter, monitorar e proteger APIs.""")
t("""AWS Aurora:	é um banco de dados relacional da Amazon Web Services, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""AWS Availability Zones:	são zonas de disponibilidade dentro de uma região da Amazon Web Services que são isoladas e independentes. Serve para fornecer alta disponibilidade e tolerância a falhas.""")
t("""AWS CDK:	é o Cloud Development Kit, um framework de desenvolvimento de infraestrutura da Amazon Web Services, que permite criar recursos de infraestrutura usando código. Serve para criar recursos de infraestrutura usando código.""")
t("""AWS CLI:	é a Command Line Interface, uma ferramenta de linha de comando que permite interagir com os serviços da Amazon Web Services. Serve para interagir com os serviços da Amazon Web Services.""")
t("""AWS CloudFormation:	é um serviço de infraestrutura como código da Amazon Web Services, que permite criar e gerenciar recursos de infraestrutura usando modelos declarativos. Serve para criar e gerenciar recursos de infraestrutura.""")
t("""AWS CloudFront:	é um serviço de CDN da Amazon Web Services, que acelera a entrega de conteúdo estático e dinâmico, melhorando o desempenho e a segurança. Serve para acelerar a entrega de conteúdo estático e dinâmico.""")
t("""AWS CloudTrail:	é um serviço de auditoria da Amazon Web Services, que registra e monitora as atividades dos usuários e dos recursos na nuvem. Serve para registrar e monitorar as atividades dos usuários e dos recursos.""")
t("""AWS CloudWatch:	é um serviço de monitoramento e observabilidade da Amazon Web Services, que permite monitorar recursos, aplicativos e serviços em tempo real. Serve para monitorar recursos, aplicativos e serviços em tempo real.""")
t("""AWS Cognito:	é um serviço de autenticação e autorização da Amazon Web Services, que permite adicionar autenticação e autorização a aplicativos web e móveis. Serve para adicionar autenticação e autorização a aplicativos.""")
t("""AWS Config:	é um serviço de conformidade da Amazon Web Services, que avalia a conformidade dos recursos em relação às políticas de segurança e governança. Serve para avaliar a conformidade dos recursos em relação às políticas de segurança e governança.""")
t("""AWS Console:	é a interface de usuário da Amazon Web Services, que permite gerenciar e monitorar os recursos na nuvem. Serve para gerenciar e monitorar os recursos na nuvem.""")
t("""AWS Direct Connect:	é um serviço de rede da Amazon Web Services, que permite conectar redes locais à nuvem por meio de uma conexão dedicada. Serve para conectar redes locais à nuvem por meio de uma conexão dedicada.""")
t("""AWS DocumentDB:	é um banco de dados de documentos da Amazon Web Services, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""AWS DynamoDB:	é um banco de dados NoSQL da Amazon Web Services, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""AWS EC2:	é o Elastic Compute Cloud, um serviço de computação em nuvem da Amazon Web Services, que fornece servidores virtuais sob demanda. Serve para fornecer servidores virtuais sob demanda.""")
t("""AWS ECR:	é o Elastic Container Registry, um serviço de registro de contêineres da Amazon Web Services, que permite armazenar, gerenciar e implantar imagens de contêineres. Serve para armazenar, gerenciar e implantar imagens de contêineres.""")
t("""AWS ECS:	é o Elastic Container Service, um serviço de orquestração de contêineres da Amazon Web Services, que permite implantar, gerenciar e escalar aplicativos em contêineres. Serve para implantar, gerenciar e escalar aplicativos em contêineres.""")
t("""AWS Edge Locations:	são locais de borda da Amazon Web Services que são usados para fornecer conteúdo e serviços de forma rápida e eficiente. Serve para fornecer conteúdo e serviços de forma rápida e eficiente.""")
t("""AWS EKS:	é o Elastic Kubernetes Service, um serviço de orquestração de contêineres da Amazon Web Services, que permite implantar, gerenciar e escalar aplicativos em contêineres. Serve para implantar, gerenciar e escalar aplicativos em contêineres.""")
t("""AWS Fargate:	é um serviço de computação sem servidor da Amazon Web Services, que permite executar contêineres sem a necessidade de gerenciar servidores. Serve para executar contêineres sem a necessidade de gerenciar servidores.""")
t("""AWS GuardDuty:	é um serviço de segurança da Amazon Web Services, que monitora a atividade maliciosa e não autorizada em contas e recursos. Serve para monitorar a atividade maliciosa e não autorizada.""")
t("""AWS IAM:	é o Identity and Access Management, um serviço de gerenciamento de identidade e acesso da Amazon Web Services, que permite controlar o acesso a recursos e serviços. Serve para controlar o acesso a recursos e serviços.""")
t("""AWS Inspector:	é um serviço de segurança da Amazon Web Services, que ajuda a identificar vulnerabilidades e violações de segurança em aplicativos e recursos. Serve para identificar vulnerabilidades e violações de segurança.""")
t("""AWS Kinesis:	é um serviço de streaming de dados da Amazon Web Services, que permite a ingestão e o processamento de grandes volumes de dados em tempo real. Serve para processar grandes volumes de dados em tempo real.""")
t("""AWS Lambda:	é um serviço de computação sem servidor da Amazon Web Services, que permite executar código em resposta a eventos, sem a necessidade de gerenciar servidores. Serve para executar código em resposta a eventos.""")
t("""AWS Linux:	é uma distribuição de código aberto do Linux que é otimizada para executar aplicativos na Amazon Web Services. Serve para executar aplicativos na Amazon Web Services.""")
t("""AWS Local Zones:	são zonas locais da Amazon Web Services que são usadas para fornecer serviços de nuvem em áreas metropolitanas. Serve para fornecer serviços de nuvem em áreas metropolitanas.""")
t("""AWS MSK:	é o Managed Streaming for Kafka, um serviço de streaming de dados da Amazon Web Services, que permite a ingestão e o processamento de grandes volumes de dados em tempo real. Serve para processar grandes volumes de dados em tempo real.""")
t("""AWS Organizations:	é um serviço de gerenciamento de contas da Amazon Web Services, que permite organizar e controlar várias contas em uma única estrutura. Serve para organizar e controlar várias contas em uma única estrutura.""")
t("""AWS RDS:	é o Relational Database Service, um serviço de banco de dados relacional da Amazon Web Services, que permite implantar, gerenciar e escalar bancos de dados relacionais. Serve para implantar, gerenciar e escalar bancos de dados relacionais.""")
t("""AWS regions:	são regiões geográficas onde a Amazon Web Services tem data centers e infraestrutura de nuvem. Serve para fornecer serviços de nuvem em diferentes regiões geográficas.""")
t("""AWS Route 53:	é um serviço de DNS da Amazon Web Services, que permite registrar domínios, rotear solicitações de DNS e monitorar a saúde dos recursos. Serve para registrar domínios, rotear solicitações de DNS e monitorar a saúde dos recursos.""")
t("""AWS S3:	é o Simple Storage Service, um serviço de armazenamento em nuvem da Amazon Web Services, que permite armazenar e recuperar dados de forma escalável e durável. Serve para armazenar e recuperar dados de forma escalável e durável.""")
t("""AWS SAM:	é o Serverless Application Model, um framework de desenvolvimento de aplicativos sem servidor da Amazon Web Services, que simplifica a criação e a implantação de aplicativos. Serve para simplificar a criação e a implantação de aplicativos sem servidor.""")
t("""AWS SDK:	é o Software Development Kit, um conjunto de ferramentas e bibliotecas que facilitam o desenvolvimento de aplicativos para a Amazon Web Services. Serve para facilitar o desenvolvimento de aplicativos para a Amazon Web Services.""")
t("""AWS SES:	é o Simple Email Service, um serviço de envio de emails da Amazon Web Services, que permite enviar emails em massa de forma segura e escalável. Serve para enviar emails em massa de forma segura e escalável.""")
t("""AWS Shield:	é um serviço de segurança da Amazon Web Services, que protege aplicativos web contra ataques DDoS. Serve para proteger aplicativos web contra ataques DDoS.""")
t("""AWS SNS:	é o Simple Notification Service, um serviço de mensagens da Amazon Web Services, que permite enviar notificações por email, SMS e outros canais. Serve para enviar notificações por email, SMS e outros canais.""")
t("""AWS SQS:	é o Simple Queue Service, um serviço de filas da Amazon Web Services, que permite a comunicação assíncrona entre aplicativos. Serve para comunicar de forma assíncrona entre aplicativos.""")
t("""AWS Step Functions:	é um serviço de orquestração de fluxo de trabalho da Amazon Web Services, que permite coordenar a execução de tarefas em aplicativos distribuídos. Serve para coordenar a execução de tarefas em aplicativos distribuídos.""")
t("""AWS Trusted Advisor:	é um serviço de otimização da Amazon Web Services, que fornece recomendações para melhorar a segurança, o desempenho e os custos dos recursos. Serve para fornecer recomendações para melhorar a segurança, o desempenho e os custos.""")
t("""AWS VPC:	é a Virtual Private Cloud, um serviço de rede da Amazon Web Services, que permite criar redes virtuais isoladas e seguras na nuvem. Serve para criar redes virtuais isoladas e seguras na nuvem.""")
t("""AWS VPN:	é o Virtual Private Network, um serviço de rede da Amazon Web Services, que permite conectar redes locais à nuvem de forma segura. Serve para conectar redes locais à nuvem de forma segura.""")
t("""AWS WAF:	é o Web Application Firewall, um serviço de segurança da Amazon Web Services, que protege aplicativos web contra ataques maliciosos. Serve para proteger aplicativos web contra ataques maliciosos.""")
t("""AWS X-Ray:	é um serviço de rastreamento da Amazon Web Services, que permite monitorar e depurar aplicativos distribuídos em tempo real. Serve para monitorar e depurar aplicativos distribuídos em tempo real.""")
t("""AWS:	é a Amazon Web Services, uma plataforma de computação em nuvem que oferece uma ampla gama de serviços, como computação, armazenamento, banco de dados e análise. Serve para oferecer serviços de computação em nuvem.""")
q(f"""Caramba {c.Teacher()}! Nossa, Quanta coisa da AWS?""")
t("""Sim, eles são enormes e aqui só tem alguns serviços... """)
t("""Azure:	é a Microsoft Azure, uma plataforma de computação em nuvem que oferece uma ampla gama de serviços, como computação, armazenamento, banco de dados e análise. Serve para oferecer serviços de computação em nuvem.""")
t("""BaaS:	é Bank as a Service, um modelo de negócios que permite que instituições financeiras ofereçam serviços bancários por meio de APIs, permitindo a integração com outras plataformas. Serve para oferecer serviços bancários por meio de APIs. Significa Bank as a Service.""")
t("""Bash:	é um shell de linha de comando e uma linguagem de script que é amplamente utilizado em sistemas Unix e Linux. Serve para interagir com o sistema operacional e executar comandos. Significa Bourne Again Shell.""")
t("""BDD:	é o desenvolvimento orientado a comportamento, uma prática de desenvolvimento de software que consiste em escrever testes baseados no comportamento esperado do sistema. Serve para escrever testes baseados no comportamento esperado do sistema. Significa Behavior Driven Development.""")
t("""Bind:	é um servidor de DNS de código aberto que é projetado para resolver consultas de DNS de forma eficiente e escalável. Serve para resolver consultas de DNS de forma eficiente e escalável.""")
t("""Bitbucket:	é uma plataforma de hospedagem de código-fonte que permite o compartilhamento e a colaboração em projetos de software. Serve para hospedar e colaborar em projetos de software.""")
t("""BSD:	é o Berkeley Software Distribution, uma família de sistemas operacionais de código aberto baseada no Unix. Serve para oferecer suporte a aplicativos e serviços. Significa Berkeley Software Distribution.""")
t("""bzip2:	é um algoritmo de compressão de código aberto que é projetado para compactar e descompactar arquivos de forma eficiente. Serve para compactar e descompactar arquivos.""")
t("""Cache:	é um mecanismo de armazenamento temporário que armazena dados frequentemente acessados, reduzindo o tempo de acesso e melhorando o desempenho. Serve para armazenar dados frequentemente acessados.""")
t("""cache:	é um mecanismo de armazenamento temporário que é usado para acelerar o acesso a dados frequentemente acessados. Serve para acelerar o acesso a dados frequentemente acessados.""")
t("""Callback:	é uma função que é passada como argumento para outra função, para ser executada posteriormente. Serve para executar uma função posteriormente.""")
t("""CD:	é a entrega contínua, um processo de desenvolvimento de software que automatiza a implantação de código em ambientes de produção. Serve para automatizar a implantação de código em ambientes de produção.""")
t("""CDN:	é uma rede de servidores distribuídos geograficamente que armazena conteúdo estático, como imagens e vídeos, para acelerar o carregamento de páginas da web. Serve para acelerar o carregamento de páginas da web.""")
t("""CentOS:	é uma distribuição de código aberto do Linux que é baseada no Red Hat Enterprise Linux e é mantida pela comunidade. Serve para oferecer uma alternativa gratuita ao Red Hat Enterprise Linux.""")
t("""CI:	é a integração contínua, um processo de desenvolvimento de software que automatiza a construção, os testes e a implantação de código. Serve para automatizar a construção, os testes e a implantação de código.""")
t("""CI/CD:	é a Integração Contínua e a Entrega Contínua, um conjunto de práticas e processos que são usados para automatizar a construção, o teste e a implantação de software. Serve para automatizar a construção, o teste e a implantação de software. Significa Continuous Integration/Continuous Delivery.""")
t("""Clean Architecture:	é uma arquitetura de software que consiste em dividir um aplicativo em camadas independentes e isoladas. Serve para dividir um aplicativo em camadas independentes e isoladas. É fundamentada por Uncle Bob no livro Clean Architecture.""")
t("""Clean Code:	é um código limpo, um código que é fácil de entender, manter e modificar. Serve para ser fácil de entender, manter e modificar. É fundamentado por Uncle Bob no livro Clean Code.""")
t("""Cloud computing:	é a entrega de serviços de computação pela internet, incluindo armazenamento, servidores, bancos de dados, rede, software, análise e inteligência, sem a necessidade de gerenciar a infraestrutura física.""")
t("""Code Review:	é o processo de revisão do código-fonte por outros desenvolvedores, para identificar erros, melhorar a qualidade e compartilhar conhecimento. Serve para revisar o código-fonte. Significa revisão de código.""")
t("""Código nativo:	é o código que é executado diretamente pelo sistema operacional, sem a necessidade de uma camada de abstração. Serve para executar código diretamente pelo sistema operacional.""")
t("""Concourse:	é uma ferramenta de automação de pipelines que permite a criação, a execução e o monitoramento de pipelines de CI/CD. Serve para automatizar pipelines de CI/CD.""")
t("""Confluence:	é uma ferramenta de colaboração que permite a criação, o compartilhamento e a organização de documentos e informações. Serve para criar, compartilhar e organizar documentos e informações.""")
t("""Container:	é um ambiente isolado que contém um aplicativo e todas as suas dependências, permitindo que ele seja executado de forma consistente em diferentes ambientes. Serve para isolar aplicativos e suas dependências.""")
q(f"""Caramba {c.Teacher()}! e temos que aprender tudo isso?""")
t("""Sim jovem tartaruga, mas se vc quiser, pode ir no Google pesquisar...""")
t("""CQRS:	é o Command Query Responsibility Segregation, um padrão de arquitetura de software que separa as operações de leitura e escrita em um aplicativo. Serve para separar as operações de leitura e escrita em um aplicativo. Significa Command Query Responsibility Segregation. É fundamentado por Greg Young no livro CQRS.""")
t("""CRUD:	é um acrônimo que significa "Create, Read, Update, Delete", que são as operações básicas de um sistema de gerenciamento de banco de dados. Serve para realizar operações básicas em um banco de dados. Significa Create, Read, Update, Delete.""")
t("""CSR:	é a renderização do lado do cliente, uma técnica que renderiza a interface do usuário no navegador, após o carregamento da página, melhorando a interatividade. Serve para renderizar a interface do usuário no navegador. Significa Client-Side Rendering.""")
t("""CSS:	é uma linguagem de estilo que é usada para estilizar páginas da web. Serve para estilizar páginas da web. Serve para estilizar páginas da web.""")
t("""csv:	é um formato de arquivo de código aberto que é projetado para armazenar e processar dados de forma eficiente. Serve para armazenar e processar dados. Consiste em arquivos de valores separados por vírgula.""")
t("""CTR:	é a taxa de cliques, uma métrica que mede a proporção de cliques em um anúncio em relação ao número de visualizações. Serve para medir a proporção de cliques em um anúncio. Significa Click-Through Rate.""")
t("""CV:	é a visão computacional, um subcampo da inteligência artificial que se concentra no desenvolvimento de sistemas que podem interpretar e analisar imagens e vídeos. Serve para desenvolver sistemas que podem interpretar e analisar imagens e vídeos. Significa Computer Vision.""")
t("""DaaS:	é a área de trabalho como serviço, um modelo de computação em nuvem que fornece desktops virtuais sob demanda, permitindo que os usuários acessem seus ambientes de trabalho de qualquer lugar. Serve para fornecer desktops virtuais sob demanda. Significa Desktop as a Service.""")
t("""Data Transfer:	é a transferência de dados entre sistemas e aplicativos para sincronizar informações e compartilhar recursos. Serve para sincronizar informações e compartilhar recursos.""")
t("""DDD:	é o design orientado a domínio, uma abordagem de design de software que se concentra no domínio do problema, em vez da tecnologia. Serve para se concentrar no domínio do problema. Significa Domain Driven Design.""")
t("""DDoS:	é um ataque de negação de serviço distribuído que sobrecarrega um servidor com tráfego malicioso, tornando-o inacessível. Serve para sobrecarregar um servidor com tráfego malicioso.""")
t("""deb:	é um formato de pacote de código aberto que é projetado para instalar e gerenciar software em sistemas Linux. Serve para instalar e gerenciar software. É nativo das distribuições Debian.""")
t("""DevOps:	é uma cultura e prática de desenvolvimento de software que enfatiza a colaboração entre desenvolvedores e operações, a automação de processos e a entrega rápida e confiável de software. Serve para colaborar entre desenvolvedores e operações, automatizar processos e entregar software rapidamente.""")
t("""DL:	é o aprendizado profundo, um subcampo do aprendizado de máquina que se concentra no desenvolvimento de redes neurais profundas e complexas. Serve para desenvolver redes neurais profundas e complexas. Significa Deep Learning.""")
t("""DNS:	é um sistema que traduz nomes de domínio em endereços IP, permitindo que os computadores se comuniquem entre si.""")
t("""DNSMasq:	é um servidor de DNS de código aberto que é projetado para resolver consultas de DNS de forma eficiente e escalável. Serve para resolver consultas de DNS de forma eficiente e escalável.""")
t("""Docker:	é uma plataforma de software que permite a criação, o teste e a implantação de aplicativos em contêineres. Serve para criar, testar e implantar aplicativos em contêineres.""")
t("""Domain-Driven Design (DDD):	é um conjunto de princípios e práticas que são usados para projetar e implementar sistemas de software baseados no domínio. Serve para projetar e implementar sistemas de software baseados no domínio. É fundamentado por Eric Evans no livro Domain-Driven Design.""")
t("""DR:	é o Disaster Recovery, um conjunto de práticas e processos que são usados para recuperar sistemas e aplicativos após uma interrupção. Serve para recuperar sistemas e aplicativos após uma interrupção. Significa Disaster Recovery.""")
t("""DRY:	é um princípio de design de software que significa "Don't Repeat Yourself", que enfatiza a reutilização de código e a eliminação de duplicação. Serve para reutilizar código e eliminar duplicação. Significa Don't Repeat Yourself.""")
t("""ElasticSearch:	é um mecanismo de busca e análise de código aberto, que permite a indexação e a pesquisa de grandes volumes de dados. Serve para indexar e pesquisar grandes volumes de dados.""")
t("""End-to-End Test:	é o processo de teste de um aplicativo em seu ambiente de produção, para garantir que ele funcione corretamente do início ao fim. Serve para testar um aplicativo em seu ambiente de produção. Significa teste de ponta a ponta.""")
t("""Event Loop:	é um mecanismo que permite que um programa execute tarefas de forma assíncrona, sem bloquear a execução. Serve para executar tarefas de forma assíncrona.""")
t("""Event Sourcing:	é um padrão de arquitetura de software que consiste em armazenar eventos de domínio como a única fonte de verdade. Serve para armazenar eventos de domínio como a única fonte de verdade. É fundamentado por Martin Fowler no livro Event Sourcing.""")
t("""Event-driven architecture (EDA):	é uma arquitetura de software que consiste em sistemas que respondem a eventos e mensagens assíncronas. Serve para responder a eventos e mensagens assíncronas.""")
t("""FaaS:	é a função como serviço, um modelo de computação em nuvem que executa funções de forma independente, sob demanda, sem a necessidade de gerenciar servidores. Serve para executar funções de forma independente. Significa Function as a Service.""")
t("""FastAPI:	é um framework de desenvolvimento de API em python de código aberto que é projetado para criar APIs de forma rápida e eficiente. Serve para criar APIs de forma rápida e eficiente. É mantido pela FastAPI. """)
t("""Firewall:	é um sistema de segurança que monitora e controla o tráfego de rede, protegendo os sistemas contra ameaças.""")
t("""Fish:	é um shell de linha de comando que é projetado para ser fácil de usar e configurar, com recursos avançados de autocompletar. Serve para interagir com o sistema operacional e executar comandos. Significa Friendly Interactive Shell.""")
t("""Flask:	é um framework de desenvolvimento web em python de código aberto que é projetado para criar aplicativos web de forma simples e eficiente. Serve para criar aplicativos web de forma simples e eficiente. É mantido pela Pallets.""")
t("""FTP:	é um protocolo de transferência de arquivos. Serve para enviar e receber arquivos pela internet.""")
q(f"""Caramba {c.Teacher()}! e temos que aprender tudo isso?""")
t("""Sim, Relaxa aí e presta atenção...""")
t("""GCP App Engine:	é um serviço de plataforma como serviço do Google Cloud Platform, que permite criar e implantar aplicativos web e móveis de forma escalável. Serve para criar e implantar aplicativos de forma escalável.""")
t("""GCP BigQuery:	é um serviço de análise de dados do Google Cloud Platform, que permite consultar e analisar grandes volumes de dados de forma rápida e eficiente. Serve para consultar e analisar grandes volumes de dados.""")
t("""GCP Cloud Armor:	é um serviço de segurança do Google Cloud Platform, que protege aplicativos web contra ataques DDoS e ameaças de segurança. Serve para proteger aplicativos web contra ataques DDoS e ameaças de segurança.""")
t("""GCP Cloud Billing:	é um serviço de faturamento do Google Cloud Platform, que permite gerenciar os custos e as despesas dos recursos na nuvem. Serve para gerenciar os custos e as despesas dos recursos na nuvem.""")
t("""GCP Cloud CDN:	é um serviço de rede de entrega de conteúdo do Google Cloud Platform, que acelera a entrega de conteúdo estático e dinâmico. Serve para acelerar a entrega de conteúdo estático e dinâmico.""")
t("""GCP Cloud Console:	é a interface de usuário do Google Cloud Platform, que permite gerenciar e monitorar os recursos na nuvem. Serve para gerenciar e monitorar os recursos na nuvem.""")
t("""GCP Cloud Debugger:	é um serviço de depuração do Google Cloud Platform, que permite depurar aplicativos em produção sem interromper o fluxo de tráfego. Serve para depurar aplicativos em produção.""")
t("""GCP Cloud Deployment Manager:	é um serviço de gerenciamento de implantação do Google Cloud Platform, que permite criar e gerenciar recursos de infraestrutura usando modelos declarativos. Serve para criar e gerenciar recursos de infraestrutura.""")
t("""GCP Cloud DNS:	é um serviço de DNS do Google Cloud Platform, que permite registrar domínios, rotear solicitações de DNS e monitorar a saúde dos recursos. Serve para registrar domínios, rotear solicitações de DNS e monitorar a saúde dos recursos.""")
t("""GCP Cloud Functions Framework:	é um framework de desenvolvimento de funções sem servidor do Google Cloud Platform, que permite criar e implantar funções de forma escalável. Serve para criar e implantar funções de forma escalável.""")
t("""GCP Cloud Functions:	é um serviço de computação sem servidor do Google Cloud Platform, que permite executar código em resposta a eventos, sem a necessidade de gerenciar servidores. Serve para executar código em resposta a eventos.""")
t("""GCP Cloud IAM:	é o Identity and Access Management do Google Cloud Platform, que permite controlar o acesso a recursos e serviços. Serve para controlar o acesso a recursos e serviços.""")
t("""GCP Cloud Identity:	é um serviço de gerenciamento de identidade do Google Cloud Platform, que permite controlar o acesso a recursos e serviços. Serve para controlar o acesso a recursos e serviços.""")
t("""GCP Cloud Interconnect:	é um serviço de interconexão do Google Cloud Platform, que permite conectar redes locais à nuvem por meio de uma conexão dedicada. Serve para conectar redes locais à nuvem por meio de uma conexão dedicada.""")
t("""GCP Cloud Load Balancing:	é um serviço de balanceamento de carga do Google Cloud Platform, que distribui o tráfego entre instâncias de aplicativos. Serve para distribuir o tráfego entre instâncias de aplicativos.""")
t("""GCP Cloud Logging:	é um serviço de registro do Google Cloud Platform, que permite armazenar, pesquisar e analisar registros de aplicativos e serviços. Serve para armazenar, pesquisar e analisar registros de aplicativos e serviços.""")
t("""GCP Cloud Monitoring:	é um serviço de monitoramento do Google Cloud Platform, que permite monitorar recursos, aplicativos e serviços em tempo real. Serve para monitorar recursos, aplicativos e serviços em tempo real.""")
t("""GCP Cloud Profiler:	é um serviço de perfil do Google Cloud Platform, que permite analisar o desempenho de aplicativos e identificar gargalos de desempenho. Serve para analisar o desempenho de aplicativos.""")
t("""GCP Cloud Router:	é um serviço de roteamento do Google Cloud Platform, que permite conectar redes locais à nuvem de forma segura. Serve para conectar redes locais à nuvem de forma segura.""")
t("""GCP Cloud Run:	é um serviço de contêineres gerenciados do Google Cloud Platform, que permite executar contêineres de forma escalável e sem servidor. Serve para executar contêineres de forma escalável e sem servidor.""")
t("""GCP Cloud Scheduler:	é um serviço de agendamento do Google Cloud Platform, que permite agendar e automatizar tarefas em aplicativos e serviços. Serve para agendar e automatizar tarefas em aplicativos e serviços.""")
t("""GCP Cloud Security Scanner:	é um serviço de segurança do Google Cloud Platform, que ajuda a identificar vulnerabilidades em aplicativos web. Serve para identificar vulnerabilidades em aplicativos web.""")
t("""GCP Cloud Storage for Firebase:	é um serviço de armazenamento em nuvem do Google Cloud Platform, que permite armazenar e recuperar dados de forma escalável e durável. Serve para armazenar e recuperar dados de forma escalável e durável.""")
t("""GCP Cloud Storage:	é um serviço de armazenamento em nuvem do Google Cloud Platform, que permite armazenar e recuperar dados de forma escalável e durável. Serve para armazenar e recuperar dados de forma escalável e durável.""")
t("""GCP Cloud Tasks:	é um serviço de fila de tarefas do Google Cloud Platform, que permite coordenar a execução de tarefas em aplicativos distribuídos. Serve para coordenar a execução de tarefas em aplicativos distribuídos.""")
t("""GCP Cloud Trace:	é um serviço de rastreamento do Google Cloud Platform, que permite monitorar e depurar aplicativos distribuídos em tempo real. Serve para monitorar e depurar aplicativos distribuídos em tempo real.""")
t("""GCP Cloud VPN:	é um serviço de rede privada virtual do Google Cloud Platform, que permite conectar redes locais à nuvem de forma segura. Serve para conectar redes locais à nuvem de forma segura.""")
t("""GCP Compute Engine:	é um serviço de computação em nuvem do Google Cloud Platform, que fornece servidores virtuais sob demanda. Serve para fornecer servidores virtuais sob demanda.""")
t("""GCP Dataflow:	é um serviço de processamento de dados em tempo real do Google Cloud Platform, que permite processar e analisar grandes volumes de dados em tempo real. Serve para processar e analisar grandes volumes de dados em tempo real.""")
t("""GCP Dataproc:	é um serviço de processamento de dados do Google Cloud Platform, que permite executar cargas de trabalho de big data em clusters de computação. Serve para executar cargas de trabalho de big data em clusters de computação.""")
t("""GCP Datastore:	é um banco de dados NoSQL do Google Cloud Platform, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""GCP Edge Locations:	são locais de borda do Google Cloud Platform que são usados para fornecer conteúdo e serviços de forma rápida e eficiente. Serve para fornecer conteúdo e serviços de forma rápida e eficiente.""")
t("""GCP Firebase AdMob:	é um serviço de monetização de aplicativos do Google Cloud Platform, que permite exibir anúncios em aplicativos e gerar receita. Serve para exibir anúncios em aplicativos e gerar receita.""")
t("""GCP Firebase App Distribution:	é um serviço de distribuição de aplicativos do Google Cloud Platform, que permite distribuir e atualizar aplicativos de forma segura. Serve para distribuir e atualizar aplicativos de forma segura.""")
t("""GCP Firebase Authentication:	é um serviço de autenticação do Google Cloud Platform, que permite adicionar autenticação a aplicativos web e móveis. Serve para adicionar autenticação a aplicativos.""")
t("""GCP Firebase Crashlytics:	é um serviço de relatórios de falhas do Google Cloud Platform, que permite monitorar e relatar falhas em aplicativos. Serve para monitorar e relatar falhas em aplicativos.""")
t("""GCP Firebase Dynamic Links:	é um serviço de links dinâmicos do Google Cloud Platform, que permite criar links inteligentes que direcionam os usuários para o conteúdo certo. Serve para criar links inteligentes que direcionam os usuários para o conteúdo certo.""")
t("""GCP Firebase Firestore:	é um banco de dados NoSQL do Google Cloud Platform, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""GCP Firebase Functions:	é um serviço de funções sem servidor do Google Cloud Platform, que permite executar código em resposta a eventos, sem a necessidade de gerenciar servidores. Serve para executar código em resposta a eventos.""")
t("""GCP Firebase Hosting:	é um serviço de hospedagem do Google Cloud Platform, que permite hospedar sites e aplicativos web de forma escalável e segura. Serve para hospedar sites e aplicativos web de forma escalável e segura.""")
t("""GCP Firebase In-App Messaging:	é um serviço de mensagens no aplicativo do Google Cloud Platform, que permite enviar mensagens personalizadas para os usuários. Serve para enviar mensagens personalizadas para os usuários.""")
t("""GCP Firebase Invites:	é um serviço de convites do Google Cloud Platform, que permite que os usuários convidem outras pessoas para usar os aplicativos. Serve para convidar outras pessoas para usar os aplicativos.""")
t("""GCP Firebase ML:	é um serviço de aprendizado de máquina do Google Cloud Platform, que permite criar e implantar modelos de aprendizado de máquina em aplicativos. Serve para criar e implantar modelos de aprendizado de máquina.""")
t("""GCP Firebase Performance Monitoring:	é um serviço de monitoramento de desempenho do Google Cloud Platform, que permite monitorar e otimizar o desempenho de aplicativos. Serve para monitorar e otimizar o desempenho de aplicativos.""")
t("""GCP Firebase Realtime Database:	é um banco de dados em tempo real do Google Cloud Platform, que oferece sincronização em tempo real e offline para aplicativos. Serve para oferecer sincronização em tempo real e offline para aplicativos.""")
t("""GCP Firebase Remote Config:	é um serviço de configuração remota do Google Cloud Platform, que permite personalizar o comportamento dos aplicativos sem a necessidade de atualizações. Serve para personalizar o comportamento dos aplicativos.""")
t("""GCP Firebase Storage:	é um serviço de armazenamento do Google Cloud Platform, que permite armazenar e recuperar arquivos de forma escalável e durável. Serve para armazenar e recuperar arquivos de forma escalável e durável.""")
t("""GCP Firebase Test Lab:	é um serviço de teste de aplicativos do Google Cloud Platform, que permite testar aplicativos em dispositivos reais e virtuais. Serve para testar aplicativos em dispositivos reais e virtuais.""")
t("""GCP Firestore:	é um banco de dados NoSQL do Google Cloud Platform, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""GCP Kubernetes Engine:	é um serviço de orquestração de contêineres do Google Cloud Platform, que permite implantar, gerenciar e escalar aplicativos em contêineres. Serve para implantar, gerenciar e escalar aplicativos em contêineres.""")
t("""GCP Memorystore:	é um serviço de armazenamento em cache do Google Cloud Platform, que permite armazenar e recuperar dados de forma rápida e eficiente. Serve para armazenar e recuperar dados de forma rápida e eficiente.""")
t("""GCP Pub-Sub:	é um serviço de mensagens do Google Cloud Platform, que permite a comunicação assíncrona entre aplicativos. Serve para comunicar de forma assíncrona entre aplicativos.""")
t("""GCP regions:	são regiões geográficas onde o Google Cloud Platform tem data centers e infraestrutura de nuvem. Serve para fornecer serviços de nuvem em diferentes regiões geográficas.""")
t("""GCP Spanner:	é um banco de dados relacional global do Google Cloud Platform, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""GCP SQL:	é um serviço de banco de dados relacional do Google Cloud Platform, que permite implantar, gerenciar e escalar bancos de dados relacionais. Serve para implantar, gerenciar e escalar bancos de dados relacionais.""")
t("""GCP zones:	são zonas dentro de uma região do Google Cloud Platform que são isoladas e independentes. Serve para fornecer alta disponibilidade e tolerância a falhas.""")
t("""GCP:	é o Google Cloud Platform, uma plataforma de computação em nuvem que oferece uma ampla gama de serviços, como computação, armazenamento, banco de dados e análise. Serve para oferecer serviços de computação em nuvem.""")
q(f"""Hoje tá longo o negócio {c.Teacher()}! """)
t("""Você sempre pode desistir e se contentar com um sub emprego qualquer ou continuar e se tornar um mestre...""")
t("""Git:	é um sistema de controle de versão distribuído que permite o rastreamento de alterações em arquivos e colaboração em projetos de software. Serve para rastrear alterações em arquivos e colaborar em projetos de software.""")
t("""GitHub:	é uma plataforma de hospedagem de código-fonte que permite o compartilhamento e a colaboração em projetos de software. Serve para hospedar e colaborar em projetos de software.""")
t("""Go Lang:	é uma linguagem de programação de código aberto que é projetada para ser simples, eficiente e escalável. Serve para desenvolver aplicativos e serviços. Significa Go Language. É mantida pelo Google.""")
t("""GraphQL:	é uma linguagem de consulta para APIs que permite que os clientes solicitem apenas os dados de que precisam, em uma única chamada. Serve para consultar APIs. Significa Graph Query Language.""")
t("""gzip:	é um algoritmo de compressão de código aberto que é projetado para compactar e descompactar arquivos de forma eficiente. Serve para compactar e descompactar arquivos.""")
t("""HA:	é a Alta Disponibilidade, um conjunto de práticas e processos que são usados para garantir que os sistemas e aplicativos estejam sempre disponíveis. Serve para garantir que os sistemas e aplicativos estejam sempre disponíveis. Significa High Availability.""")
t("""HAProxy:	é um balanceador de carga de código aberto que é projetado para distribuir o tráfego entre servidores de forma eficiente e escalável. Serve para distribuir o tráfego entre servidores de forma eficiente e escalável.""")
t("""Hexagonal architecture:	é uma arquitetura de software que consiste em dividir um aplicativo em camadas concêntricas e independentes. Serve para dividir um aplicativo em camadas concêntricas e independentes. É fundamentada por Alistair Cockburn no livro Hexagonal Architecture.""")
t("""HTML:	é uma linguagem de marcação que é usada para criar páginas da web. Serve para criar páginas da web. Serve para criar páginas da web.""")
t("""HTTP:	é um protocolo de comunicação que permite a transferência de informações na web, como páginas da web.""")
t("""HTTPS:	é uma versão segura do protocolo HTTP, que criptografa as informações transferidas, garantindo mais segurança.""")
t("""Hypervisor:	é um software que permite a criação e a execução de máquinas virtuais em um servidor físico. Serve para criar e executar máquinas virtuais. Serve para criar e executar máquinas virtuais.""")
t("""IaaS:	é a infraestrutura como serviço, um modelo de computação em nuvem que fornece recursos de infraestrutura, como servidores virtuais e armazenamento, sob demanda. Serve para fornecer recursos de infraestrutura sob demanda. Significa Infrastructure as a Service.""")
t("""IaC:	é a infraestrutura como código, uma prática que automatiza a criação, a configuração e a gestão de infraestrutura de TI usando código. Serve para automatizar a criação, a configuração e a gestão de infraestrutura de TI. Siginifica Infrastructure as Code.""")
t("""Insomnia:	é uma ferramenta de desenvolvimento de API que é usada para testar e depurar APIs de forma eficiente. Serve para testar e depurar APIs. É mantida pela Kong.""")
t("""Integration Test:	é o processo de teste da integração entre diferentes unidades de código, para garantir que elas funcionem juntas corretamente. Serve para testar a integração entre diferentes unidades de código. Significa teste de integração.""")
t("""IP:	é um número que identifica um dispositivo em uma rede, permitindo que ele se comunique com outros dispositivos.""")
t("""IPv4:	é a quarta versão do protocolo de internet, que usa endereços de 32 bits, permitindo 4 bilhões de endereços.""")
t("""IPv6:	é a sexta versão do protocolo de internet, que usa endereços de 128 bits, permitindo mais endereços.""")
t("""IT ops:	é a operação de TI, um conjunto de práticas e processos que são usados para gerenciar e manter sistemas de TI. Serve para gerenciar e manter sistemas de TI. Significa Information Technology Operations.""")
q(f"""Uau {c.Teacher()}! De onde saiu tanto nome??""")
t("""Você ficaria impressionado se soubesse que aqui só estão uns poucos""") 
t("""Java:	é uma linguagem de programação de código aberto que é projetada para ser simples, segura e portátil. Serve para desenvolver aplicativos e serviços. É mantida pela Oracle.""")
t("""JavaScript:	é uma linguagem de programação de código aberto que é projetada para ser dinâmica, interativa e orientada a objetos. Serve para desenvolver aplicativos e serviços. É mantida pela ECMA International.""")
t("""JavaScript:	é uma linguagem de programação que é usada para criar interatividade em páginas da web. Serve para criar interatividade em páginas da web.""")
t("""Jetbrains IntelliJ IDEA:	é um ambiente de desenvolvimento integrado que oferece suporte a várias linguagens de programação e ferramentas para desenvolvimento de software. Serve para desenvolver software. Significa IntelliJ Integrated Development Environment for Java.""")
t("""Jetbrains PyCharm:	é um ambiente de desenvolvimento integrado que oferece suporte a várias linguagens de programação e ferramentas para desenvolvimento de software. Serve para desenvolver software. Significa Python Charm.""")
t("""Jetbrains Rider:	é um ambiente de desenvolvimento integrado que oferece suporte a várias linguagens de programação e ferramentas para desenvolvimento de software. Serve para desenvolver software. Significa Rider.""")
t("""jets-streaming:	é um sistema de streaming de código aberto, que permite a comunicação assíncrona entre aplicativos. Serve para comunicar de forma assíncrona entre aplicativos. É responsável pela parte de streaming do NATS. É a evolução do nats-streaming.""")
t("""Jira:	é uma ferramenta de gerenciamento de projetos que permite o planejamento, o rastreamento e a colaboração em projetos de software. Serve para planejar, rastrear e colaborar em projetos de software.""")
t("""JSON:	é um formato de dados leve e fácil de ler, que é usado para transmitir informações entre sistemas. Serve para enviar e receber dados entre sistemas.""")
t("""Kafka Streams:	é uma biblioteca de processamento de eventos de código aberto, que permite a análise de dados em tempo real. Serve para analisar dados em tempo real.""")
t("""Kafka:	é uma plataforma de streaming de código aberto, que permite a ingestão e o processamento de grandes volumes de dados em tempo real. Serve para processar grandes volumes de dados em tempo real.""")
t("""Kanban:	é um método ágil de gerenciamento de fluxo de trabalho que enfatiza a visualização, a limitação do trabalho em progresso e a melhoria contínua. Serve para gerenciar fluxos de trabalho de forma visual, limitada e contínua.""")
t("""KISS:	é um princípio de design de software que significa "Keep It Simple, Stupid", que enfatiza a simplicidade e a clareza do código. Serve para enfatizar a simplicidade e a clareza do código. Significa Keep It Simple, Stupid.""")
t("""Kotlin:	é uma linguagem de programação de código aberto que é projetada para ser concisa, segura e interoperável com o Java. Serve para desenvolver aplicativos e serviços. É mantida pela JetBrains.""")
t("""KPI:	é o Key Performance Indicator, uma métrica que é usada para avaliar o desempenho e o sucesso de uma organização ou projeto. Serve para avaliar o desempenho e o sucesso. Significa Key Performance Indicator.""")
t("""Kubernetes:	é uma plataforma de orquestração de contêineres que automatiza a implantação, a escalabilidade e a operação de aplicativos em contêineres. Serve para automatizar a implantação, a escalabilidade e a operação de aplicativos em contêineres.""")
t("""Layered architecture:	é uma arquitetura de software que consiste em dividir um aplicativo em camadas lógicas e separadas. Serve para dividir um aplicativo em camadas lógicas e separadas.""")
t("""Lean:	é uma abordagem de gestão que busca eliminar desperdícios, melhorar a eficiência e entregar valor ao cliente. Serve para eliminar desperdícios, melhorar a eficiência e entregar valor.""")
t("""Legacy:	é um termo usado para descrever sistemas ou aplicativos antigos, que podem ser difíceis de manter ou atualizar. Serve para descrever sistemas ou aplicativos antigos. Significa legado.""")
t("""Linux:	é um sistema operacional de código aberto que é amplamente utilizado em servidores e dispositivos embarcados. Serve para oferecer suporte a aplicativos e serviços.""")
t("""LLM:	é o Low-Level Machine Learning, um conjunto de técnicas e algoritmos que são usados para treinar modelos de aprendizado de máquina em nível baixo. Serve para treinar modelos de aprendizado de máquina em nível baixo. Significa Low-Level Machine Learning.""")
t("""Load Balancer:	é um dispositivo ou software que distribui o tráfego de rede entre vários servidores, garantindo a disponibilidade e o desempenho dos aplicativos. Serve para distribuir o tráfego de rede entre servidores.""")
t("""logs:	são registros de eventos e atividades que são gerados por sistemas e aplicativos para fins de monitoramento e auditoria. Serve para monitorar e auditar sistemas e aplicativos.""")
t("""LSB:	é o Linux Standard Base, um conjunto de especificações que define a estrutura e o comportamento dos sistemas Linux. Serve para definir a estrutura e o comportamento dos sistemas Linux. Significa Linux Standard Base.""")
t("""MacOS:	é um sistema operacional da Apple que é amplamente utilizado em computadores pessoais e servidores. Serve para oferecer suporte a aplicativos e serviços.""")
t("""metrics:	são medidas quantitativas que são usadas para monitorar o desempenho e o comportamento de sistemas e aplicativos. Serve para monitorar o desempenho e o comportamento de sistemas e aplicativos.""")
t("""MFA:	é a autenticação de múltiplos fatores, um método de segurança que requer mais de uma forma de autenticação para verificar a identidade do usuário. Serve para verificar a identidade do usuário. Significa Multi-Factor Authentication.""")
t("""micro editor:	é um editor de texto de linha de comando que é projetado para ser fácil de usar e configurar, com uma interface minimalista. Serve para editar arquivos de texto. Significa micro editor.""")
t("""Microservices architecture (microservices):	é uma arquitetura de software que consiste em dividir um aplicativo em serviços independentes e escaláveis. Serve para dividir um aplicativo em serviços independentes e escaláveis.""")
t("""Microservices:	são uma abordagem arquitetônica que divide um aplicativo em serviços independentes, que se comunicam entre si por meio de APIs. Serve para dividir um aplicativo em serviços independentes. Significa microsserviços.""")
t("""Microsoft SQL Server:	é um sistema de gerenciamento de banco de dados relacional da Microsoft que oferece suporte a aplicativos e serviços de banco de dados. Serve para oferecer suporte a aplicativos e serviços de banco de dados.""")
t("""Microsoft Visual Studio Code:	é um editor de código-fonte que oferece suporte a várias linguagens de programação e extensões para desenvolvimento de software. Serve para desenvolver software. Significa Visual Studio Code.""")
t("""Microsoft Visual Studio IDE:	é um ambiente de desenvolvimento integrado que oferece suporte a várias linguagens de programação e ferramentas para desenvolvimento de software. Serve para desenvolver software. Significa Visual Studio Integrated Development Environment.""")
t("""Microsoft Windows:	é um sistema operacional da Microsoft que é amplamente utilizado em computadores pessoais e servidores. Serve para oferecer suporte a aplicativos e serviços.""")
q(f"""Caramba {c.Teacher()}! e temos que aprender tudo isso?""")
t("""Não, eu só vim aqui te encher o saco com nomes aleatórios... é claro que precisa! Relaxa aí e presta atenção... tá com preguiça?""")
t("""ML:	é o aprendizado de máquina, um subcampo da inteligência artificial que se concentra no desenvolvimento de algoritmos e modelos que podem aprender e melhorar com o tempo. Serve para desenvolver algoritmos e modelos que podem aprender e melhorar com o tempo. Significa Machine Learning.""")
t("""Mongo Atlas:	é um serviço de banco de dados gerenciado baseado em nuvem, que oferece escalabilidade, segurança e disponibilidade. Serve para gerenciar bancos de dados NoSQL.""")
t("""MongoDB:	é um banco de dados NoSQL de código aberto, orientado a documentos. Serve para gerenciar bancos de dados NoSQL. """)
t("""monitoring:	é o monitoramento de sistemas e aplicativos para garantir que eles estejam funcionando corretamente e atendendo aos requisitos de desempenho. Serve para garantir que os sistemas e aplicativos estejam funcionando corretamente.""")
t("""Monolith:	é uma abordagem arquitetônica que desenvolve um aplicativo como uma única unidade, sem dividir em serviços independentes. Serve para desenvolver um aplicativo como uma única unidade. Significa monólito.""")
t("""Monolithic architecture (monolith):	é uma arquitetura de software que consiste em um único aplicativo que é desenvolvido e implantado como uma unidade. Serve para desenvolver e implantar um único aplicativo como uma unidade.""")
t("""MQTT:	é um protocolo de mensagens leve, que permite a comunicação assíncrona entre dispositivos IoT. Serve para comunicar de forma assíncrona entre dispositivos IoT. Significa Message Queuing Telemetry Transport.""")
t("""MTBF:	é o Mean Time Between Failures, uma métrica que define o tempo médio entre falhas de um sistema ou componente. Serve para definir o tempo médio entre falhas. Significa Mean Time Between Failures.""")
t("""MTTF:	é o Mean Time To Failure, uma métrica que define o tempo médio até a falha de um sistema ou componente. Serve para definir o tempo médio até a falha. Significa Mean Time To Failure.""")
t("""MTTR:	é o Mean Time To Recovery, uma métrica que define o tempo médio necessário para recuperar um serviço ou aplicativo após uma interrupção. Serve para definir o tempo médio necessário para recuperar um serviço ou aplicativo. Significa Mean Time To Recovery.""")
t("""MVC:	é um padrão de arquitetura de software que divide um aplicativo em três componentes principais:	Modelo, Visão e Controlador. Serve para dividir um aplicativo em três componentes principais. Significa Model-View-Controller.""")
t("""MVP:	é o produto mínimo viável, uma versão simplificada de um produto que contém apenas as funcionalidades essenciais. Serve para criar uma versão simplificada de um produto. Significa Minimum Viable Product.""")
t("""MVVM:	é um padrão de arquitetura de software que divide um aplicativo em três componentes principais:	Modelo, Visão e Modelo de Visão. Serve para dividir um aplicativo em três componentes principais. Significa Model-View-ViewModel.""")
t("""MVW:	é um padrão de arquitetura de software que divide um aplicativo em três componentes principais:	Modelo, Visão e Qualquer coisa. Serve para dividir um aplicativo em três componentes principais. Significa Model-View-Whatever.""")
t("""MySQL:	é um sistema de gerenciamento de banco de dados relacional de código aberto. Serve para gerenciar bancos de dados relacionais. """)
t("""nano:	é um editor de texto de linha de comando que é projetado para ser fácil de usar e configurar, com uma interface intuitiva. Serve para editar arquivos de texto. Significa Nano's ANOther editor.""")
t("""nats-streaming:	é um sistema de streaming de código aberto, que permite a comunicação assíncrona entre aplicativos. Serve para comunicar de forma assíncrona entre aplicativos. É responsável pela parte de streaming do NATS. Foi descontinuado e substituído pelo Jets.io.""")
t("""Nats.io:	é um sistema de mensagens de código aberto, que permite a comunicação assíncrona entre aplicativos. Serve para comunicar de forma assíncrona entre aplicativos.""")
t("""neovim:	é um editor de texto de linha de comando que é uma versão moderna e extensível do vim, com recursos avançados e suporte a plugins. Serve para editar arquivos de texto. Significa Neo Vim.""")
t("""Nginx:	é um servidor web de código aberto que é projetado para servir conteúdo web de forma eficiente e escalável. Serve para servir conteúdo web de forma eficiente e escalável.""")
t("""NLP:	é o processamento de linguagem natural, um subcampo da inteligência artificial que se concentra no desenvolvimento de sistemas que podem entender e gerar linguagem humana. Serve para desenvolver sistemas que podem entender e gerar linguagem humana. Significa Natural Language Processing.""")
t("""NoSQL:	é uma categoria de bancos de dados que não seguem o modelo relacional tradicional, permitindo a flexibilidade e a escalabilidade de dados. Serve para armazenar e acessar dados de forma flexível e escalável.""")
t("""Objective-C:	é uma linguagem de programação desenvolvida pela Apple para criar aplicativos iOS, macOS, watchOS e tvOS. Serve para criar aplicativos para dispositivos Apple.""")
t("""observability:	é a capacidade de entender e depurar sistemas complexos por meio de métricas, logs e rastreamento. Serve para entender e depurar sistemas complexos.""")
q(f"""...""")
t("""Se tá achando ruim, pq veio aqui? Aguenta aí, faltam só uns 500...""")
t("""OCI Archive Storage:	é um serviço de armazenamento de arquivos da Oracle Cloud Infrastructure, que permite armazenar e recuperar dados de forma econômica. Serve para armazenar e recuperar dados de forma econômica.""")
t("""OCI Availability Domains:	são domínios de disponibilidade dentro de uma região da Oracle Cloud Infrastructure que são isolados e independentes. Serve para fornecer alta disponibilidade e tolerância a falhas.""")
t("""OCI Block Volume:	é um serviço de armazenamento em bloco da Oracle Cloud Infrastructure, que permite armazenar e recuperar dados de forma escalável e durável. Serve para armazenar e recuperar dados de forma escalável e durável.""")
t("""OCI Budgets:	é um serviço de orçamento da Oracle Cloud Infrastructure, que permite definir e monitorar os custos e as despesas dos recursos na nuvem. Serve para definir e monitorar os custos e as despesas dos recursos na nuvem.""")
t("""OCI Cloud Marketplace:	é um mercado de aplicativos da Oracle Cloud Infrastructure, que permite descobrir, implantar e gerenciar aplicativos na nuvem. Serve para descobrir, implantar e gerenciar aplicativos na nuvem.""")
t("""OCI Cloud Shell:	é um shell de linha de comando baseado em nuvem da Oracle Cloud Infrastructure, que permite interagir com os serviços da nuvem. Serve para interagir com os serviços da nuvem.""")
t("""OCI Compute:	é o Oracle Cloud Infrastructure Compute, um serviço de computação em nuvem da Oracle, que fornece servidores virtuais sob demanda. Serve para fornecer servidores virtuais sob demanda.""")
t("""OCI Container Engine:	é um serviço de orquestração de contêineres da Oracle Cloud Infrastructure, que permite implantar, gerenciar e escalar aplicativos em contêineres. Serve para implantar, gerenciar e escalar aplicativos em contêineres.""")
t("""OCI Container Registry:	é um serviço de registro de contêineres da Oracle Cloud Infrastructure, que permite armazenar, gerenciar e implantar imagens de contêineres. Serve para armazenar, gerenciar e implantar imagens de contêineres.""")
t("""OCI Cost Analysis:	é um serviço de análise de custos da Oracle Cloud Infrastructure, que permite analisar e otimizar os custos dos recursos na nuvem. Serve para analisar e otimizar os custos dos recursos na nuvem.""")
t("""OCI Data Warehouse:	é um serviço de data warehouse da Oracle Cloud Infrastructure, que permite armazenar e analisar grandes volumes de dados de forma rápida e eficiente. Serve para armazenar e analisar grandes volumes de dados.""")
t("""OCI Database:	é um serviço de banco de dados da Oracle Cloud Infrastructure, que permite implantar, gerenciar e escalar bancos de dados relacionais e NoSQL. Serve para implantar, gerenciar e escalar bancos de dados.""")
t("""OCI DNS:	é um serviço de DNS da Oracle Cloud Infrastructure, que permite registrar domínios, rotear solicitações de DNS e monitorar a saúde dos recursos. Serve para registrar domínios, rotear solicitações de DNS e monitorar a saúde dos recursos.""")
t("""OCI Edge Locations:	são locais de borda da Oracle Cloud Infrastructure que são usados para fornecer conteúdo e serviços de forma rápida e eficiente. Serve para fornecer conteúdo e serviços de forma rápida e eficiente.""")
t("""OCI Events:	é um serviço de eventos da Oracle Cloud Infrastructure, que permite monitorar e responder a eventos em tempo real. Serve para monitorar e responder a eventos em tempo real.""")
t("""OCI Exadata:	é um serviço de banco de dados da Oracle Cloud Infrastructure que oferece desempenho e escalabilidade para aplicativos de missão crítica. Serve para oferecer desempenho e escalabilidade para aplicativos de missão crítica.""")
t("""OCI FastConnect Locations:	são locais de conexão de rede da Oracle Cloud Infrastructure que são usados para conectar redes locais à nuvem. Serve para conectar redes locais à nuvem.""")
t("""OCI FastConnect:	é um serviço de conexão de rede da Oracle Cloud Infrastructure, que permite conectar redes locais à nuvem por meio de uma conexão dedicada. Serve para conectar redes locais à nuvem por meio de uma conexão dedicada.""")
t("""OCI File Storage:	é um serviço de armazenamento de arquivos da Oracle Cloud Infrastructure, que permite armazenar e compartilhar arquivos de forma escalável e durável. Serve para armazenar e compartilhar arquivos de forma escalável e durável.""")
t("""OCI Functions:	é um serviço de funções sem servidor da Oracle Cloud Infrastructure, que permite executar código em resposta a eventos, sem a necessidade de gerenciar servidores. Serve para executar código em resposta a eventos.""")
t("""OCI IAM:	é o Identity and Access Management da Oracle Cloud Infrastructure, que permite controlar o acesso a recursos e serviços. Serve para controlar o acesso a recursos e serviços.""")
t("""OCI Kubernetes Engine:	é um serviço de orquestração de contêineres da Oracle Cloud Infrastructure, que permite implantar, gerenciar e escalar aplicativos em contêineres. Serve para implantar, gerenciar e escalar aplicativos em contêineres.""")
t("""OCI Load Balancer:	é um serviço de balanceamento de carga da Oracle Cloud Infrastructure, que distribui o tráfego entre instâncias de aplicativos. Serve para distribuir o tráfego entre instâncias de aplicativos.""")
t("""OCI Local Peering Locations:	são locais de interconexão da Oracle Cloud Infrastructure que são usados para conectar redes locais à nuvem. Serve para conectar redes locais à nuvem.""")
t("""OCI Logging:	é um serviço de registro da Oracle Cloud Infrastructure, que permite armazenar, pesquisar e analisar registros de aplicativos e serviços. Serve para armazenar, pesquisar e analisar registros de aplicativos e serviços.""")
t("""OCI Monitoring:	é um serviço de monitoramento da Oracle Cloud Infrastructure, que permite monitorar recursos, aplicativos e serviços em tempo real. Serve para monitorar recursos, aplicativos e serviços em tempo real.""")
t("""OCI MySQL:	é um serviço de banco de dados MySQL da Oracle Cloud Infrastructure, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""OCI NoSQL:	é um serviço de banco de dados NoSQL da Oracle Cloud Infrastructure, que oferece escalabilidade, desempenho e disponibilidade para aplicativos modernos. Serve para oferecer escalabilidade, desempenho e disponibilidade para aplicativos modernos.""")
t("""OCI Notifications:	é um serviço de notificações da Oracle Cloud Infrastructure, que permite enviar notificações por email, SMS e outros canais. Serve para enviar notificações por email, SMS e outros canais.""")
t("""OCI Notifications:	é um serviço de notificações da Oracle Cloud Infrastructure, que permite enviar notificações por email, SMS e outros canais. Serve para enviar notificações por email, SMS e outros canais.""")
t("""OCI Object Storage:	é um serviço de armazenamento de objetos da Oracle Cloud Infrastructure, que permite armazenar e recuperar dados de forma escalável e durável. Serve para armazenar e recuperar dados de forma escalável e durável.""")
t("""OCI regions:	são regiões geográficas onde a Oracle Cloud Infrastructure tem data centers e infraestrutura de nuvem. Serve para fornecer serviços de nuvem em diferentes regiões geográficas.""")
t("""OCI Resource Manager:	é um serviço de gerenciamento de recursos da Oracle Cloud Infrastructure, que permite criar, gerenciar e compartilhar recursos de infraestrutura. Serve para criar, gerenciar e compartilhar recursos de infraestrutura.""")
t("""OCI Security:	é um serviço de segurança da Oracle Cloud Infrastructure, que protege aplicativos e dados contra ameaças de segurança. Serve para proteger aplicativos e dados contra ameaças de segurança.""")
t("""OCI Service Connector Hub:	é um serviço de conectividade da Oracle Cloud Infrastructure, que permite conectar recursos e serviços em nuvens públicas e privadas. Serve para conectar recursos e serviços em nuvens públicas e privadas.""")
t("""OCI Streaming:	é um serviço de streaming de dados da Oracle Cloud Infrastructure, que permite a ingestão e o processamento de grandes volumes de dados em tempo real. Serve para processar grandes volumes de dados em tempo real.""")
t("""OCI VPN:	é o Virtual Private Network da Oracle Cloud Infrastructure, que permite conectar redes locais à nuvem de forma segura. Serve para conectar redes locais à nuvem de forma segura.""")
t("""OCI WAF:	é o Web Application Firewall da Oracle Cloud Infrastructure, que protege aplicativos web contra ataques maliciosos. Serve para proteger aplicativos web contra ataques maliciosos.""")
t("""OCI:	é a Oracle Cloud Infrastructure, uma plataforma de computação em nuvem que oferece uma ampla gama de serviços, como computação, armazenamento, banco de dados e análise. Serve para oferecer serviços de computação em nuvem.""")
t("""ODM:	é um mapeador objeto-documento, uma técnica que mapeia objetos de um sistema orientado a objetos para documentos de um banco de dados NoSQL. Serve para mapear objetos de um sistema orientado a objetos para documentos de um banco de dados NoSQL. Significa Object-Document Mapping.""")
t("""Oh-my-zsh:	é um framework de configuração do Zsh que fornece temas, plugins e atalhos para melhorar a experiência do usuário. Serve para melhorar a experiência do usuário. Significa Oh My Zsh.""")
q(f"""Poxa {c.Teacher()}, Isso nunca termina?""")
t("""Vai terminar quando acabar, dá próxima vez, tenta aprender sozinho e veja se é mais fácil...""")
t("""OKR:	é o Objectives and Key Results, um framework de definição de metas que é usado para alinhar e medir o desempenho organizacional. Serve para alinhar e medir o desempenho organizacional. Significa Objectives and Key Results.""")
t("""Onion architecture:	é uma arquitetura de software que consiste em dividir um aplicativo em camadas concêntricas e independentes. Serve para dividir um aplicativo em camadas concêntricas e independentes. É fundamentada por Jeffrey Palermo no livro Onion Architecture.""")
t("""OpenAPI:	é uma especificação de API de código aberto que é usada para descrever e documentar APIs de forma eficiente. Serve para descrever e documentar APIs. É mantida pela OpenAPI Initiative.""")
t("""OpenFinance:	é um movimento que visa democratizar o acesso a serviços financeiros por meio de tecnologias abertas e inovadoras. Serve para democratizar o acesso a serviços financeiros. Significa Open Finance.""")
t("""Oracle Database:	é um sistema de gerenciamento de banco de dados relacional desenvolvido pela Oracle. Serve para gerenciar bancos de dados relacionais.""")
t("""Oracle:	é uma empresa de tecnologia que oferece uma ampla gama de produtos e serviços, como bancos de dados, aplicativos empresariais e computação em nuvem. Serve para oferecer produtos e serviços de tecnologia.""")
t("""ORC:	é um formato de arquivo de código aberto que é projetado para armazenar e processar grandes conjuntos de dados de forma eficiente. Serve para armazenar e processar grandes conjuntos de dados. É mantido pela Apache.""")
t("""ORM:	é um mapeador objeto-relacional, uma técnica que mapeia objetos de um sistema orientado a objetos para tabelas de um banco de dados relacional. Serve para mapear objetos de um sistema orientado a objetos para tabelas de um banco de dados relacional. Significa Object-Relational Mapping.""")
t("""PaaS:	é a plataforma como serviço, um modelo de computação em nuvem que fornece uma plataforma de desenvolvimento e implantação de aplicativos, sem a necessidade de gerenciar a infraestrutura subjacente. Serve para fornecer uma plataforma de desenvolvimento e implantação de aplicativos. Significa Platform as a Service.""")
t("""Parquet:	é um formato de arquivo de código aberto que é projetado para armazenar e processar grandes conjuntos de dados de forma eficiente. Serve para armazenar e processar grandes conjuntos de dados. É mantido pela Apache.""")
t("""pkg:	é um formato de pacote de código aberto que é projetado para instalar e gerenciar software em sistemas MacOS. Serve para instalar e gerenciar software. É nativo dos sistemas MacOS.""")
t("""POSIX:	é o Portable Operating System Interface, um conjunto de padrões que define a interface entre sistemas operacionais e aplicativos. Serve para definir a interface entre sistemas operacionais e aplicativos. Significa Portable Operating System Interface.""")
t("""Postgres:	é um sistema de gerenciamento de banco de dados relacional de código aberto. Serve para gerenciar bancos de dados relacionais. É um SGDB muito poderoso e largamente utilizado e suportado pela comunidade de tecnologia.""")
t("""Postman:	é uma ferramenta de desenvolvimento de API que é usada para testar e depurar APIs de forma eficiente. Serve para testar e depurar APIs. É mantida pela Postman.""")
t("""Power DNS:	é um servidor de DNS de código aberto que é projetado para resolver consultas de DNS de forma eficiente e escalável. Serve para resolver consultas de DNS de forma eficiente e escalável.""")
t("""PowerShell:	é uma interface de linha de comando e uma linguagem de script que é amplamente utilizado em sistemas Windows. Serve para interagir com o sistema operacional e executar comandos. Significa PowerShell.""")
t("""Prometheus:	é um sistema de monitoramento de código aberto que é projetado para coletar, armazenar e consultar métricas de sistemas e aplicativos. Serve para coletar, armazenar e consultar métricas. É mantido pela CNCF.""")
t("""Promise:	é um objeto que representa o resultado, ou a falha, de uma operação assíncrona, permitindo o tratamento de erros e o encadeamento de operações. Serve para representar o resultado de uma operação assíncrona.""")
t("""Proxy:	é um servidor que atua como intermediário entre os clientes e os servidores, permitindo o acesso a recursos de rede de forma segura e anônima. Serve para acessar recursos de rede de forma segura e anônima.""")
t("""PWA:	é um aplicativo web progressivo, uma aplicação web que oferece uma experiência semelhante a um aplicativo nativo, com recursos como notificações push e acesso offline. Serve para oferecer uma experiência semelhante a um aplicativo nativo.""")
t("""Python:	é uma linguagem de programação de código aberto que é projetada para ser simples, legível e expressiva. Serve para desenvolver aplicativos e serviços. É mantida pela Python Software Foundation.""")
t("""RabbitMQ:	é um sistema de mensagens de código aberto, que permite a comunicação assíncrona entre aplicativos. Serve para comunicar de forma assíncrona entre aplicativos.""")
t("""RDBMS:	é um sistema de gerenciamento de banco de dados relacional que armazena dados em tabelas relacionadas. Serve para armazenar e acessar dados relacionais.""")
t("""Red Hat:	é uma empresa de software que oferece soluções de código aberto para empresas, incluindo o sistema operacional Red Hat Enterprise Linux. Serve para oferecer soluções de código aberto para empresas. É mantido pela IBM.""")
t("""Redis:	é um banco de dados em memória de código aberto, que armazena dados na RAM, permitindo o acesso rápido e eficiente. Serve para armazenar dados na RAM.""")
t("""Refactoring:	é o processo de reestruturar o código-fonte de um aplicativo, sem alterar seu comportamento externo, para torná-lo mais legível, eficiente e fácil de manter. Serve para reestruturar o código-fonte de um aplicativo. Significa refatoração.""")
t("""Remote Procedure Call:	é uma técnica que permite a execução de procedimentos em um sistema remoto, como se fossem locais. Serve para executar procedimentos em um sistema remoto.""")
t("""Requisição assincrona:	é uma requisição que não bloqueia a execução do programa, permitindo que outras tarefas sejam executadas enquanto aguarda a resposta. Serve para não bloquear a execução do programa.""")
t("""Requisição sincrona:	é uma requisição que bloqueia a execução do programa até que a resposta seja recebida. Serve para bloquear a execução do programa até que a resposta seja recebida.""")
t("""REST/RESTful:	é um estilo de arquitetura de software que define um conjunto de restrições para a criação de serviços web, como a utilização de métodos HTTP e a representação de recursos. Serve para criar serviços web. Significa Representational State Transfer.""")
t("""Reverse Proxy:	é um servidor que atua como intermediário entre os clientes e os servidores, ocultando a complexidade da infraestrutura e melhorando o desempenho e a segurança. Serve para ocultar a complexidade da infraestrutura.""")
t("""RL:	é o aprendizado por reforço, um subcampo do aprendizado de máquina que se concentra no desenvolvimento de agentes inteligentes que podem aprender com base em recompensas e punições. Serve para desenvolver agentes inteligentes que podem aprender com base em recompensas e punições. Significa Reinforcement Learning.""")
t("""rpm:	é um formato de pacote de código aberto que é projetado para instalar e gerenciar software em sistemas Linux. Serve para instalar e gerenciar software. É nativo das distribuições Red Hat.""")
t("""RPO:	é o Recovery Point Objective, uma métrica que define o tempo máximo permitido para perder dados após uma interrupção. Serve para definir o tempo máximo permitido para perder dados. Significa Recovery Point Objective.""")
t("""RTO:	é o Recovery Time Objective, uma métrica que define o tempo máximo permitido para recuperar um serviço ou aplicativo após uma interrupção. Serve para definir o tempo máximo permitido para recuperar um serviço ou aplicativo. Significa Recovery Time Objective.""")
q(f"""{c.Teacher()}, Letra R ainda?!""")
t("""Sim, pelo menos o alfabeto vc conhece, né?""")
t("""SaaS:	é o software como serviço, um modelo de computação em nuvem que fornece aplicativos baseados na web sob demanda, sem a necessidade de instalação ou manutenção local. Serve para fornecer aplicativos baseados na web sob demanda. Significa Software as a Service.""")
t("""Script:	é um conjunto de comandos que são executados sequencialmente para automatizar tarefas repetitivas. Serve para automatizar tarefas repetitivas.""")
t("""Scrum:	é um framework ágil de gerenciamento de projetos que enfatiza a colaboração, a transparência, a adaptação e a entrega incremental. Serve para gerenciar projetos de forma colaborativa, transparente, adaptativa e incremental.""")
t("""SEM:	é o marketing de mecanismos de busca, um conjunto de práticas que promovem um site nos resultados dos mecanismos de busca, por meio de anúncios pagos. Serve para promover um site nos resultados dos mecanismos de busca. Significa Search Engine Marketing.""")
t("""SEO:	é a otimização para mecanismos de busca, um conjunto de práticas que melhoram a visibilidade de um site nos resultados dos mecanismos de busca. Serve para melhorar a visibilidade de um site nos resultados dos mecanismos de busca. Significa Search Engine Optimization.""")
t("""Serverless architecture (serverless):	é uma arquitetura de software que consiste em executar código em resposta a eventos, sem a necessidade de gerenciar servidores. Serve para executar código em resposta a eventos.""")
t("""Serverless:	é um modelo de computação em nuvem que executa funções de forma independente, sob demanda, sem a necessidade de gerenciar servidores. Serve para executar funções de forma independente. Significa sem servidor.""")
t("""Service-oriented architecture (SOA):	é uma arquitetura de software que consiste em serviços independentes e reutilizáveis que são conectados por meio de interfaces. Serve para conectar serviços independentes e reutilizáveis por meio de interfaces.""")
t("""Sharding:	é uma técnica de banco de dados que consiste em dividir dados em fragmentos menores e distribuí-los em vários servidores. Serve para distribuir dados em vários servidores.""")
t("""Shell:	é uma interface de linha de comando que permite interagir com o sistema operacional e executar comandos. Serve para interagir com o sistema operacional e executar comandos.""")
t("""SLA:	é o Service Level Agreement, um contrato que define os níveis de serviço e as responsabilidades entre um provedor de serviços e um cliente. Serve para definir os níveis de serviço e as responsabilidades. Significa Service Level Agreement.""")
t("""SLI:	é o Service Level Indicator, uma métrica que é usada para medir o desempenho e a disponibilidade de um serviço ou aplicativo. Serve para medir o desempenho e a disponibilidade. Significa Service Level Indicator.""")
t("""SLO:	é o Service Level Objective, uma métrica que define os níveis de serviço desejados para um serviço ou aplicativo. Serve para definir os níveis de serviço desejados. Significa Service Level Objective.""")
t("""SMM:	é o marketing de mídias sociais, um conjunto de práticas que promovem um site nas mídias sociais, por meio de anúncios pagos. Serve para promover um site nas mídias sociais. Significa Social Media Marketing.""")
t("""SMO:	é a otimização de mídias sociais, um conjunto de práticas que melhoram a visibilidade de um site nas mídias sociais. Serve para melhorar a visibilidade de um site nas mídias sociais. Significa Social Media Optimization.""")
t("""SOAP:	é um protocolo de comunicação baseado em XML que permite a troca de mensagens entre sistemas distribuídos. Serve para trocar mensagens entre sistemas distribuídos. Significa Simple Object Access Protocol.""")
t("""Socket:	é um ponto de comunicação entre dois processos em uma rede, permitindo a troca de dados, como um telefone. Serve para enviar e receber dados entre processos.""")
t("""Software architecture:	é a arquitetura de software, um conjunto de princípios e práticas que são usados para projetar e implementar sistemas de software. Serve para projetar e implementar sistemas de software.""")
t("""SOLID:	é um conjunto de princípios de design de software que visam tornar o código mais legível, sustentável e fácil de manter. Serve para tornar o código mais legível, sustentável e fácil de manter. Significa Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion.""")
t("""SPA:	é um aplicativo de página única, uma aplicação web que carrega uma única página e atualiza o conteúdo dinamicamente, sem recarregar a página inteira. Serve para carregar uma única página e atualizar o conteúdo dinamicamente. Significa Single Page Application.""")
t("""Splunk:	é uma plataforma de análise de dados que permite a busca, a monitoração e a visualização de dados em tempo real. Serve para analisar dados em tempo real.""")
t("""Sprint:	é um período de tempo fixo em que uma equipe de desenvolvimento trabalha em um conjunto de tarefas, geralmente de 1 a 4 semanas. Serve para trabalhar em um conjunto de tarefas em um período de tempo fixo.""")
t("""SQL:	é uma linguagem de consulta estruturada que é usada para acessar e manipular bancos de dados relacionais. Serve para acessar e manipular bancos de dados relacionais.""")
t("""SQLite:	é um sistema de gerenciamento de banco de dados relacional de código aberto. Serve para gerenciar bancos de dados relacionais. É um SGDB que roda localmente e é muito utilizado em aplicações mobile ou de pequeno porte.""")
t("""SRE:	é a engenharia de confiabilidade de sites, uma disciplina que combina desenvolvimento de software e operações para criar sistemas confiáveis e escaláveis. Serve para criar sistemas confiáveis e escaláveis. Significa Site Reliability Engineering.""")
t("""SSH:	é um protocolo de comunicação seguro. Serve para acessar servidores remotamente.""")
t("""SSR:	é a renderização do lado do servidor, uma técnica que renderiza a interface do usuário no servidor e a envia para o navegador, melhorando o desempenho e a experiência do usuário. Serve para renderizar a interface do usuário no servidor. Significa Server-Side Rendering.""")
t("""Streamings:	é um modelo de comunicação que permite a transmissão de dados em tempo real, de forma contínua. Serve para transmitir dados em tempo real.""")
t("""Sublime Text:	é um editor de código-fonte que oferece suporte a várias linguagens de programação e extensões para desenvolvimento de software. Serve para desenvolver software. Significa Sublime Text.""")
t("""Swagger:	é uma ferramenta de desenvolvimento de API que é usada para documentar e testar APIs de forma eficiente. Serve para documentar e testar APIs. É mantida pela SmartBear Software.""")
t("""Swift language:	é uma linguagem de programação desenvolvida pela Apple para criar aplicativos iOS, macOS, watchOS e tvOS. Serve para criar aplicativos para dispositivos Apple.""")
t("""System architecture:	é a arquitetura de sistemas, um conjunto de princípios e práticas que são usados para projetar e implementar sistemas de software e hardware. Serve para projetar e implementar sistemas de software e hardware.""")
q(f"""{c.Teacher()}, S nunca termina...""")
t("""Quer q eu pare? Não né?""")
t("""tar:	é um formato de arquivo de código aberto que é projetado para agrupar e comprimir arquivos de forma eficiente. Serve para agrupar e comprimir arquivos.""")
t("""TCP:	é um protocolo de comunicação que permite que diferentes computadores se comuniquem entre si, garantindo a entrega de dados.""")
t("""tcpdump:	é uma ferramenta de linha de comando que é usada para capturar e analisar pacotes de rede em sistemas Unix e Linux. Serve para capturar e analisar pacotes de rede.""")
t("""TDD:	é o desenvolvimento orientado a testes, uma prática de desenvolvimento de software que consiste em escrever testes antes de escrever o código de produção. Serve para escrever testes antes de escrever o código de produção. Significa Test Driven Development.""")
t("""Telnet:	é um protocolo de comunicação não seguro, que permite acessar servidores remotamente.""")
t("""Terminal:	é uma interface de linha de comando que permite interagir com o sistema operacional e executar comandos. Serve para interagir com o sistema operacional e executar comandos.""")
t("""Terraform:	é uma ferramenta de infraestrutura como código que permite criar, gerenciar e provisionar recursos de infraestrutura de forma declarativa. Serve para criar, gerenciar e provisionar recursos de infraestrutura de forma declarativa. É mantido pela HashiCorp.""")
t("""tracing:	é o rastreamento de solicitações e transações em sistemas distribuídos para identificar gargalos e problemas de desempenho. Serve para identificar gargalos e problemas de desempenho.""")
t("""tsv:	é um formato de arquivo de código aberto que é projetado para armazenar e processar dados de forma eficiente. Serve para armazenar e processar dados. Consiste em arquivos de valores separados por tabulação.""")
t("""Unit Test:	é o processo de teste de unidades individuais de código, para garantir que cada unidade funcione corretamente. Serve para testar unidades individuais de código. Significa teste de unidade.""")
t("""Unix:	é um sistema operacional de código aberto que é amplamente utilizado em servidores e sistemas embarcados. Serve para oferecer suporte a aplicativos e serviços.""")
t("""User Story:	é uma descrição curta de uma funcionalidade do software, escrita do ponto de vista do usuário, que descreve o que o usuário deseja alcançar. Serve para descrever funcionalidades do software do ponto de vista do usuário.""")
q(f"""{c.Teacher()}, como vc consegue? Dá onde vem tanta vontade?""")
t("""Eu gosto disso, vc deveria tentar tbm... mas café ajuda bastante...""")
t("""vi:	é um editor de texto de linha de comando que é amplamente utilizado em sistemas Unix e Linux. Serve para editar arquivos de texto. Significa Visual Editor.""")
t("""VictoriaMetrics:	é um sistema de monitoramento de código aberto que é projetado para coletar, armazenar e consultar métricas de sistemas e aplicativos. Serve para coletar, armazenar e consultar métricas. É mantido pela VictoriaMetrics.""")
t("""vim:	é um editor de texto de linha de comando que é uma versão melhorada do vi, com recursos adicionais e melhorias de usabilidade. Serve para editar arquivos de texto. Significa Vi IMproved.""")
t("""Virtualization:	é a criação de ambientes virtuais que imitam um sistema de hardware, permitindo a execução de vários sistemas operacionais em um único servidor físico. Serve para criar ambientes virtuais.""")
t("""VPN:	é uma rede privada virtual que permite que os usuários acessem a internet de forma segura e privada, criptografando a conexão.""")
t("""WAF:	é o Web Application Firewall, um firewall de aplicativos web que protege aplicativos contra ataques maliciosos. Serve para proteger aplicativos contra ataques maliciosos. Significa Web Application Firewall.""")
t("""Waterfall:	é um modelo de desenvolvimento de software sequencial que divide o projeto em fases, como requisitos, design, implementação, testes e manutenção. Serve para dividir o projeto em fases sequenciais.""")
t("""Web App:	é um aplicativo desenvolvido para ser executado em um navegador da web. Serve para criar aplicativos para navegadores da web.""")
t("""WebRTC:	é uma tecnologia que permite a comunicação em tempo real entre navegadores da web, por meio de uma conexão ponto a ponto. Serve para comunicar em tempo real entre navegadores da web.""")
t("""WebSockets:	é uma tecnologia que permite a comunicação bidirecional e em tempo real entre um cliente e um servidor, por meio de uma conexão persistente. Serve para comunicar em tempo real entre um cliente e um servidor.""")
t("""Windows Server:	é um sistema operacional de servidor da Microsoft que oferece suporte a aplicativos e serviços de servidor. Serve para oferecer suporte a aplicativos e serviços de servidor.""")
t("""xls:	é um formato de arquivo de código aberto que é projetado para armazenar e processar planilhas de dados de forma eficiente. Serve para armazenar e processar planilhas de dados.""")
t("""xlsx:	é um formato de arquivo de código aberto que é projetado para armazenar e processar planilhas de dados de forma eficiente. Serve para armazenar e processar planilhas de dados.""")
t("""XML:	é uma linguagem de marcação que permite a criação de documentos estruturados, que são fáceis de ler e interpretar. Serve para criar documentos estruturados.""")
t("""YAGNI:	é um princípio de design de software que significa "You Aren't Gonna Need It", que enfatiza a implementação de funcionalidades apenas quando necessário. Serve para implementar funcionalidades apenas quando necessário. Significa You Aren't Gonna Need It.""")
t("""YAML:	é uma linguagem de serialização de dados que é usada para representar informações de forma legível para humanos. Serve para representar informações de forma legível para humanos.""")
t("""ZeroMQ:	é uma biblioteca de mensagens de código aberto, que permite a comunicação assíncrona entre aplicativos. Serve para comunicar de forma assíncrona entre aplicativos.""")
t("""zip:	é um formato de arquivo de código aberto que é projetado para compactar e descompactar arquivos de forma eficiente. Serve para compactar e descompactar arquivos.""")
t("""Zsh:	é um shell de linha de comando que é uma extensão do Bash, com recursos adicionais e melhorias de usabilidade. Serve para interagir com o sistema operacional e executar comandos. Significa Z Shell.""")
t("""ZSTD:	é um algoritmo de compressão de código aberto que é projetado para comprimir e descomprimir dados de forma eficiente. Serve para comprimir e descomprimir dados. É mantido pela Facebook.""") 
q(f"""{c.Teacher()}, uau! Z finalmente...""")
t("""Sim, agora vc já sabe o alfabeto inteiro... e muitos termos técnicos importantes, agora pode descansar...""")