FROM ubuntu:latest

RUN apt update -y \
    && apt install -y git ttyd vim python3 python3-pygments cron \
    && apt autoremove -y \
    && apt autoclean -y \
    && rm -rf /var/lib/apt/lists/* 

RUN touch crontab /etc/cron.d/crontab \
    && chmod 0644 /etc/cron.d/crontab \
    && touch /var/log/cron.log \
    && echo "0 * * * * /srv/learn-ops-content/update.sh >> /var/log/cron.log 2>&1" >> /etc/cron.d/crontab \

RUN cd /srv \
    && git clone https://github.com/RafaelFino/learn-ops-content 

WORKDIR /srv/learn-ops-content/src

EXPOSE 5002

ENTRYPOINT [ "/srv/learn-ops-content/ttyd-server.sh" ]